###
POST http://localhost:8004/frequent/createFrequentFood
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

Pizza
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="pizza.jpg"
Content-Type: image/jpeg

< ./backend/assets/food-1050813_1280.jpg
--WebAppBoundary--


####
POST http://localhost:8004/frequent/createFrequentFood
Content-Type: application/json

{
  "name": "Pizza",
  "imageUrl": [
    "https://images.unsplash.com/photo-1601924582975-4f3c1d0f2e3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGl6emF8ZW58MHx8MHx8fDA%3D&w=1000&q=80"
  ]
}